FORMAT: 1A
HOST: http://test.euda.com.ar/ochoescalones/dev

# L8E v2

API interna para los clientes del juego Los 8 Escalones.

## Info [/v2/info]

### Versiones de cliente & servidor [POST /v2/info/version?p={platform_id}]

+ Parameters
    + platform_id (required, enum[number]) - ID de la plataforma del client
        + Members
            + 1 - Web
            + 2 - Android
            + 3 - iOS

+ Response 200 (application/json)

        {
            "clientVersion": "1.4.0",
            "serverVersion": "2.0.0",
            "mandatory": "false"
        }

## Questions [/v2/questions]

### Bundle de preguntas [POST /v2/questions/bundle?user_id={user_id}]

+ Parameters
    + user_id (required, number) - ID del usuario

+ Response 200 (application/json)

        {
            "clientVersion": "1.4.0",
            "serverVersion": "2.0.0",
            "mandatory": "false"
        }