FORMAT: 1A
HOST: http://test.euda.com.ar/ochoescalones/dev

# L8E v2

API interna para los clientes del juego Los 8 Escalones.

## Info [/v2/info]

### Versiones de cliente & servidor [POST /v2/info/version?p={platform_id}]

+ Parameters
    + platform_id (required, enum[number]) - ID de la plataforma del client
        + Members
            + 1 - Web
            + 2 - Android
            + 3 - iOS

+ Response 200 (application/json)

        {
            "clientVersion": "1.4.0",
            "serverVersion": "2.0.0",
            "mandatory": "false"
        }

## Questions [/v2/questions]

### Crear pregunta del usuario [POST /v2/questions/]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }