FORMAT: 1A
HOST: http://test.euda.com.ar/ochoescalones/dev

# L8E v2

API interna para los clientes del juego Los 8 Escalones.

## Info [/v2/info]

### Versiones de cliente & servidor [POST /v2/info/version?p={platform_id}]

+ Parameters
    + platform_id (required, enum[number]) - ID de la plataforma del client
        + Members
            + 1 - Web
            + 2 - Android
            + 3 - iOS

+ Response 200 (application/json)

        {
            "clientVersion": "1.4.0",
            "serverVersion": "2.0.0",
            "mandatory": "false"
        }

## Updates [/v2/updates]

### Actualizar el usuario a la v2 [POST /v2/updates/toV2?user_id={user_id}]

+ Parameters
    + user_id (required, number) - ID del usuario

+ Response 200

        {
            "success": true
        }

## Questions [/v2/questions]

### Bundle de preguntas [POST /v2/questions/bundle?user_id={user_id}]

+ Parameters
    + user_id (required, number) - ID del usuario

+ Response 200 (application/json)

        {
            "questions": [{
                "id": 288,
                "question": "\u00bfEn el cementerio de qu\u00e9 ciudad fue oculto el cad\u00e1ver de Eva Per\u00f3n luego de ser sustra\u00eddo en 1955?",
                "rightAnswer": "Mil\u00e1n",
                "extraAnswers": ["Roma", "Berl\u00edn", "Madrid"],
                "level": 3,
                "category": "historia",
                "subcategory": "personajes_historicos"
            }, {
                "id": 495,
                "question": "\u00bfQu\u00e9 lago se encuentra en la frontera entre Per\u00fa y Bolivia?",
                "rightAnswer": "Titicaca",
                "extraAnswers": ["Poop\u00f3", "Hur\u00f3n", "Baikal"],
                "level": 1,
                "category": "geografia",
                "subcategory": "paisajes"
            }, {
                "id": 1220,
                "question": "\u00bfCu\u00e1l de estas opciones se vincula directamente con la llamada \u201cTeor\u00eda del caos\u201d?",
                "rightAnswer": "Efecto mariposa",
                "extraAnswers": ["Efecto invernadero", "Efecto suelo", "Efecto Magnus"],
                "level": 2,
                "category": "ciencia",
                "subcategory": "fisica_y_quimica"
            }, {
                "id": 903,
                "question": "\u00bfEn cu\u00e1l de estas obras el protagonista vende su alma al diablo a cambio de juventud eterna?",
                "rightAnswer": "Fausto",
                "extraAnswers": ["El alquimista", "El fantasma de Canterville", "Frankenstein"],
                "level": 2,
                "category": "artes",
                "subcategory": "literatura"
            }, {
                "id": 914,
                "question": "\u00bfCu\u00e1l de estas personalidades aparece en la tapa del famoso disco de Los Beatles \u201cSargent Pepper\u00b4s\u201d?",
                "rightAnswer": "Karl Marx",
                "extraAnswers": ["Mahatma Gandhi", "Madre Teresa de Calcuta", "Mick Jagger"],
                "level": 3,
                "category": "entretenimiento",
                "subcategory": "famosos"
            }, {
                "id": 46,
                "question": "\u00bfCu\u00e1l de estos seres vivos es clasificado formalmente como insecto?",
                "rightAnswer": "Avispa",
                "extraAnswers": ["Ciempi\u00e9s", "Ara\u00f1a", "Escorpi\u00f3n"],
                "level": 3,
                "category": "ciencia",
                "subcategory": "biologia"
            }, {
                "id": 754,
                "question": "\u00bfQu\u00e9 revolucionario artefacto inventaron los Hermanos Lumi\u00e9re?",
                "rightAnswer": "Cinemat\u00f3grafo",
                "extraAnswers": ["Motor de combusti\u00f3n", "Gram\u00f3fono", "Telegraf\u00eda sin hilos"],
                "level": 3,
                "category": "historia",
                "subcategory": "personajes_historicos"
            }, {
                "id": 753,
                "question": "\u00bfCual es tu medida preferida?",
                "rightAnswer": "Todas las anteriores",
                "extraAnswers": ["12 inches", "7 inches", "9 inches"],
                "level": 3,
                "category": "entretenimiento",
                "subcategory": "famosos"
            }]
        }
        
## Matches [/v2/matches]

### Crear match [POST /v2/matches/create?userid={user_id}&opponentid={opponent_id}&answers={answers}&time={time}$isrematch={is_rematch}]

+ Parameters
    + user_id (required, number) - ID del usuario.
    + opponent_id (required, number) - ID del oponente.
    + answers (required, string) - Respuestas del usuario, tienen que ser 8.
    + time (required, number) - Tiempo total de las respuestas en milisegundos.
    + is_rematch (optional, bool) - Si es una revancha o no.

+ Response 200 (application/json)

        {
            "id": 1,
            "opponentId": 1002,
            "yourStep": 7,
            "opponentStep": 0,
            "yourPoints": 35,
            "opponentPoints": 0,
            "yourTime": 15000,
            "opponentTime": 0,
            "yourName": "Guche",
            "opponentName": "Otro Gato"
        }

### Update match [POST /v2/matches/update?id={match_id}&userid={user_id}&answers={answers}]

+ Parameters
    + match_id (required, number) - ID del match.
    + user_id (required, number) - ID del usuario.
    + answers (required, string) - Respuestas del usuario, tienen que ser 8.

+ Response 200 (application/json)

        {
            "id": 1,
            "opponentId": 1001,
            "yourStep": 8,
            "opponentStep": 7,
            "yourPoints": 40,
            "opponentPoints": 35,
            "yourTime": 15000,
            "opponentTime": 14500,
            "yourName": "Otro Gato",
            "opponentName": "Guche"
        }